### ISSUE TITLE
possible typo in course-details.md file

### ISSUE THREAD

**Issue by chandrakishorSingh** [githubtraining/community-starter-kit#26]
From the Prerequisites section of course-details.md file
> In this course you will work with issues and pull requests, as well as edit files. If these things are familiar to you, we recommend you take the [Introduction to GitHub]({{ host }}/githubtraining/introduction-to-github) course, first!

In the second sentence, do you mean "If these things are *not* familiar to you, we recommend you take the [Introduction to GitHub]({{ host }}/githubtraining/introduction-to-github) course, first!" instead ?

**Comment by brianamarie** [comment]
Thank you for opening this issue, @chandrakishorSingh! Would you be interested in opening a pull request with the fix to [this file](https://github.com/githubtraining/community-starter-kit/blob/main/course-details.md)?

**Comment by chandrakishorSingh** [comment]
Sure @brianamarie

**Comment by chandrakishorSingh** [comment]
Thanks for accepting the changes @brianamarie! Closing this issue now.
