### ISSUE TITLE
Wrong URL in `responses/08n-next.md` file

### ISSUE THREAD

**Issue by chandrakishorSingh** [githubtraining/community-starter-kit#28]
## Bug Report

**Current behavior**
The URL mentioned in the following message points to a pull request `https://github.com/<username>/community-starter-kit/pull/8`
> All of the necessary files are complete! Now we just need to help Mona get eyes eyes on her project. I have a few ideas that might help and I've dropped them in this issue.

**Reproduction**
Steps to reproduce the behavior in the course:
1. Enroll into the [community starter kit](https://lab.github.com/githubtraining/community-starter-kit) course.
2. Complete all the steps up to step 14 "Merge the Code of Conduct"
3. When this 14th step is completed, the following message by [github learning lab](https://github.com/marketplace/github-learning-lab) bot will be displayed.
> All of the necessary files are complete! Now we just need to help Mona get eyes eyes on her project. I have a few ideas that might help and I've dropped them in `this issue`.
4. When clicked on `this issue`, instead of redirecting to the required issue, it redirects the user to a pull request(the same one on which the above message is displayed).

**Expected behavior**
The URL mentioned in the above message should point to an issue `https://github.com/<username>/community-starter-kit/issues/9`

**Possible solution**
I have checked the response of the github-learning-lab bot in this [file](https://github.com/githubtraining/community-starter-kit/blob/main/responses/08n-next.md) and it appears that the link stored in the `issueURL` variable might be incorrect. Although the link stored in the `store.visibilityIssueUrl` variable is correct(which is used in another response of bot just below the original one). So, replacing `issueURL` variable by `store.visibilityIssueUrl` should work.

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chandrakishorSingh** [comment]
I have made PR #29 with the possible solution mentioned in the bug report. Can you review it @brianamarie ?

**Comment by brianamarie** [comment]
Fixed in #29 & #30. Thank you, @chandrakishorSingh!
